name: mms_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  logger: ^1.0.0
  share: ^2.0.1
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  url_launcher: ^6.0.8
  flutter_keyboard_visibility: 3.3.0
  firebase_core: ^1.6.0
  firebase_database:
  cloud_firestore: ^2.5.1
  firebase_auth: ^3.1.0
  another_flushbar: ^1.10.20
  firebase_storage: ^10.0.3
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  keyboard_attachable:
  flutter_svg:
  google_sign_in:
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^5.0.0+4
  eva_icons_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: "#F43DE3"
  image: images/logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - images/