name: mms_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+117

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  logger: ^1.0.0
  share_plus:
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  firebase_core: ^1.10.6
  firebase_database:
  cloud_firestore: ^2.5.1
  firebase_auth: ^3.1.0
  another_flushbar: ^1.10.20
  google_sign_in: ^5.1.0
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^5.0.0+4
  grouped_list: ^4.1.0
  firebase_analytics: ^7.0.1
  ntp: ^2.0.0
  image_picker:
  cached_network_image:
  firebase_storage:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: "#8745c3"
  image: images/logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - images/